### ISSUE TITLE
Use Wii Mote for Boot Selection

### ISSUE THREAD

**Issue by Veggieoskibroski** [wiiu-env/Tiramisu#10]
Make it possible to select/confirm options in the Tiramisu Boot Selector using any Wii remote. This would be helpful when you want to just play a Wii game and no more, or play some non-gamepad required Wii U games

**Comment by Maschell** [comment]
This is already a TODO on my list, the "problem" currently is that it would delay the boot time in order to reliable wait for a wiimote connection. 

I'll close this issue and open a new issue in the [AutobootModule](https://github.com/wiiu-env/AutobootModule) which is responsible for handling the boot menu
